---
services:
  searchnos:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: searchnos
    environment:
      - PORT=3000
      - SRC_RELAYS=${SRC_RELAYS}
      - FETCH_KINDS=${FETCH_KINDS}
      - NEGENTROPY_RELAYS=${NEGENTROPY_RELAYS}
      - NEGENTROPY_DAYS=${NEGENTROPY_DAYS}
      - SEARCHNOS_DB_PATH=/data
    restart: always
    ports:
      - 3000:3000
    volumes:
      - searchnos-db-data:/data

volumes:
  searchnos-db-data:
    driver: local
